name: dxvk-gplasync-master.sh CI

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: bootstraps.yml
          workflow_conclusion: success
          path: /opt
      - name: Build dxvk-gplasync
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          sudo apt install glslang-tools meson -y
          sudo apt install mingw-w64 build-essential -y 
          cd ~
          git clone --depth 1 https://gitlab.com/Ph42oN/dxvk-gplasync.git dxvk-gplasync
          git clone --recursive https://github.com/doitsujin/dxvk.git dxvk
          cp ~/dxvk-gplasync/patches/dxvk-gplasync-master.patch ~/dxvk
          cd dxvk
          patch -p 1 -i dxvk-gplasync-master.patch
          ./package-release.sh master /opt/dxvk-gplasync-master --no-package
          cd /opt/
          tar -cjvf dxvk-gplasync-master.tar.xz dxvk-gplasync-master
          sha256sum /opt/*.tar.xz
      - uses: actions/upload-artifact@v3
        with:
          name: dxvk-gplasync-master
          path: /opt/*.tar.xz
