name: Build Mesa for ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 镜像
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up ARM64 Docker container
        run: |
          docker run --rm --privileged --platform linux/arm64 -v $(pwd):/workspace -w /workspace arm64v8/ubuntu:latest bash -c "
            apt-get update &&
            apt-get install -y build-essential cmake meson ninja-build libdrm-dev libxcb1-dev libx11-dev libxext-dev libxdamage-dev libvulkan-dev libgbm-dev libglvnd-dev libegl1-mesa-dev pkg-config &&
            mkdir -p build &&
            cd build &&
            meson .. --prefix=/usr --buildtype=release &&
            ninja &&
            sudo ninja install"
          
      - name: Verify installation
        run: |
          docker run --rm --privileged --platform linux/arm64 arm64v8/ubuntu:latest glxinfo | grep "OpenGL version"
