name: update-mesa.sh CI

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: bootstraps.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          chmod +x update-mesa.sh
          ./update-mesa.sh
          sha256sum *.tar.xz
      - name: Package mesa directory
        run: |
          tar -cJf mesa-25.0.0-devel-armhf.tar.xz -C ~/ mesa/
      - name: Upload mesa artifact
      - uses: actions/upload-artifact@v3
        with:
          name: mesa-25.0.0-devel-armhf
          path: ./*.tar.xz
